version: '3.9'
services:
  # nginx:
  #   image: nginx
  #   volumes:
  #     - ./default.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - "80:80"
  #     - "443:443"
  redis:
    image: redis
    command: redis-server --save 60 --loglevel warning
    volumes:
      - ./Docker/Redis-Docker/redis-data:/var/lib/redis
    ports:
      - "6379:6379"
  lambda:
    build:
      context: .
      dockerfile: Docker/Lambda-Docker/Dockerfile
  bot:
    build:
      context: .
      dockerfile: Docker/Bot-Docker/Dockerfile
    env_file: .env
      
